apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springtest
  name: springtest
  namespace: randomapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springtest
    spec:
      containers:
      - image: islamifauzi/springtest:1
        imagePullPolicy: IfNotPresent
        name: springtest
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
